[[im_systemd_fields]]
===== Fields

The following fields are used by _im_systemd_.

[[im_systemd_field_raw_event]]
`$raw_event` (type: <<lang_type_string,string>>)::
+
--
A list of event fields in key-value pairs.
--

[[im_systemd_field_AuditSession]]
`$AuditSession` (type: <<lang_type_string,string>>)::
+
--
Session of the process the journal entry originates from,
          as maintained by the kernel audit subsystem.
--

[[im_systemd_field_AuditUID]]
`$AuditUID` (type: <<lang_type_string,string>>)::
+
--
Login UID of the process the journal entry originates from,
          as maintained by the kernel audit subsystem.
--

`$AuditUID` (type: <<lang_type_string,string>>)::
+
--
Login UID of the process the journal entry originates from,
          as maintained by the kernel audit subsystem.
--

[[im_systemd_field_BootID]]
`$BootID` (type: <<lang_type_string,string>>)::
+
--
Kernel boot ID for the boot the message was
          generated in, formatted as a 128-bit hexadecimal string.
--

[[im_systemd_field_Capabilities]]
`$Capabilities` (type: <<lang_type_string,string>>)::
+
--
Effective capabilities of the process the journal entry originates
          from.
--

[[im_systemd_field_CodeFile]]
`$CodeFile` (type: <<lang_type_string,string>>)::
+
--
Code location to generate this message, if known.
        Contains the source filename.
--

[[im_systemd_field_CodeFunc]]
`$CodeFunc` (type: <<lang_type_string,string>>)::
+
--
Code location to generate this message, if known.
          Contains the function name.
--

[[im_systemd_field_CodeLine]]
`$CodeLine` (type: <<lang_type_integer,integer>>)::
+
--
Code location to generate this message, if known.
          Contains the line number.
--

[[im_systemd_field_CoredumpUnit]]
`$CoredumpUnit` (type: <<lang_type_string,string>>)::
+
--
Annotation to the message in case it contains coredumps from system
          and session units.
--

[[im_systemd_field_CoredumpUserUnit]]
`$CoredumpUserUnit` (type: <<lang_type_string,string>>)::
+
--
Annotation to the message in case it contains coredumps from system
          and session units.
--

[[im_systemd_field_DevLink]]
`$DevLink` (type: <<lang_type_string,string>>)::
+
--
Additional symlink names pointing to the device node under the '/dev'
          directory.
--

[[im_systemd_field_DevName]]
`$DevName` (type: <<lang_type_string,string>>)::
+
--
Device name of the kernel as it shows up in the device tree under the
          '/sys' directory.
--

[[im_systemd_field_DevNode]]
`$DevNode` (type: <<lang_type_string,string>>)::
+
--
Node path of the device under the '/dev' directory.
--

[[im_systemd_field_Errno]]
`$Errno` (type: <<lang_type_integer,integer>>)::
+
--
Low-level Unix error number which caused the entry, if any.
          Contains the numeric value of 'errno' formatted as a decimal string.
--

[[im_systemd_field_EventTime]]
`$EventTime` (type: <<lang_type_datetime,datetime>>)::
+
--
The earliest trusted timestamp of the message,
          if any is known that is different from the reception
          time of the journal.
--

[[im_systemd_field_Facility]]
`$Facility` (type: <<lang_type_string,string>>)::
+
--
Syslog compatibility fields containing the facility.
--

[[im_systemd_field_Group]]
`$Group` (type: <<lang_type_string,string>>)::
+
--
Group ID of the process the journal entry originates from.
--

[[im_systemd_field_Hostname]]
`$Hostname` (type: <<lang_type_string,string>>)::
+
--
The name of the originating host.
--

[[im_systemd_field_KernelDevice]]
`$KernelDevice` (type: <<lang_type_string,string>>)::
+
--
Device name of the kernel.
          If the entry is associated to a block device, the field contains the
          major and minor of the device node, separated by ":" and prefixed by
          "b". Similar for character devices but prefixed by "c". For network
          devices, this is the interface index prefixed by "n". For all other
          devices, this is the subsystem name prefixed by "+", followed by ":",
          followed by the kernel device name.
--

[[im_systemd_field_KernelSubsystem]]
`$KernelSubsystem` (type: <<lang_type_string,string>>)::
+
--
Subsystem name of the kernel.
--

[[im_systemd_field_MachineID]]
`$MachineID` (type: <<lang_type_string,string>>)::
+
--
Machine ID of the originating host.
--

[[im_systemd_field_Message]]
`$Message` (type: <<lang_type_string,string>>)::
+
--
A human-readable message string for the current entry.
      	This is supposed to be the primary text shown to the user.
      	This is usually not translated (but might be in some cases),
      	and not supposed to be parsed for metadata.
--

[[im_systemd_field_MessageID]]
`$MessageID` (type: <<lang_type_string,string>>)::
+
--
A 128-bit message identifier for recognizing certain message
        types, if this is desirable. This should contain a 128-bit identifier
        formatted as a lower-case hexadecimal string, without any
        separating dashes or suchlike. This is recommended to be
        a UUID-compatible ID, but this is not enforced, and formatted
        differently.
--

[[im_systemd_field_ObjAuditSession]]
`$ObjAuditSession` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'AuditSession', except that
          the process identified by PID is described, instead of the process
          which logged the message.
--

[[im_systemd_field_ObjAuditUID]]
`$ObjAuditUID` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'AuditUID', except that
          the process identified by PID is described, instead of the process
          which logged the message.
--

[[im_systemd_field_ObjGroup]]
`$ObjGroup` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'Group', except that the
          process identified by PID is described, instead of the process which
          logged the message.
--

[[im_systemd_field_ObjProcessCmdLine]]
`$ObjProcessCmdLine` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'ProcessCmdLine', except
          that the process identified by PID is described, instead of the
          process which logged the message.
--

[[im_systemd_field_ObjProcessExecutable]]
`$ObjProcessExecutable` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'ProcessExecutable', except
          that the process identified by PID is described, instead of the
          process which logged the message.
--

[[im_systemd_field_ObjProcessID]]
`$ObjProcessID` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'ProcessID', except that the
          process identified by PID is described, instead of the process which
          logged the message.
--

[[im_systemd_field_ObjProcessName]]
`$ObjProcessName` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'ProcessName', except that
          the process identified by PID is described, instead of the process
          which logged the message.
--

[[im_systemd_field_ObjSystemdCGroup]]
`$ObjSystemdCGroup` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'SystemdCGroup', except
          that the process identified by PID is described, instead of the
          process which logged the message.
--

[[im_systemd_field_ObjSystemdOwnerUID]]
`$ObjSystemdOwnerUID` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'SystemdOwnerUID', except
          that the process identified by PID is described, instead of the
          process which logged the message.
--

[[im_systemd_field_ObjSystemdSession]]
`$ObjSystemdSession` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'SystemdSession', except
          that the process identified by PID is described, instead of the
          process which logged the message.
--

[[im_systemd_field_ObjSystemdUnit]]
`$ObjSystemdUnit` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'SystemdUnit', except that
          the process identified by PID is described, instead of the process
          which logged the message.
--

[[im_systemd_field_ObjUser]]
`$ObjUser` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same value as the 'User', except that the
          process identified by PID is described, instead of the process which
          logged the message.
--

`$ObjUser` (type: <<lang_type_integer,integer>>)::
+
--
This field contains the same name as the 'User', except that the
          process identified by PID is described, instead of the process which
          logged the message.
--

[[im_systemd_field_ProcessCmdLine]]
`$ProcessCmdLine` (type: <<lang_type_string,string>>)::
+
--
Command line of the process the journal entry originates from.
--

[[im_systemd_field_ProcessExecutable]]
`$ProcessExecutable` (type: <<lang_type_string,string>>)::
+
--
Executable path of the process the journal entry originates from.
--

[[im_systemd_field_ProcessID]]
`$ProcessID` (type: <<lang_type_string,string>>)::
+
--
Syslog compatibility field containing the client PID.
--

[[im_systemd_field_ProcessName]]
`$ProcessName` (type: <<lang_type_string,string>>)::
+
--
Name of the process the journal entry originates from.
--

[[im_systemd_field_SelinuxContext]]
`$SelinuxContext` (type: <<lang_type_string,string>>)::
+
--
SELinux security context (label) of the process the journal entry
          originates from.
--

[[im_systemd_field_Severity]]
`$Severity` (type: <<lang_type_string,string>>)::
+
--
A priority value between 0 ("emerg") and 7 ("debug")
        formatted as a string. This field is compatible with
        syslog's priority concept.
--

[[im_systemd_field_SeverityValue]]
`$SeverityValue` (type: <<lang_type_integer,integer>>)::
+
--
A priority value between 0 ("emerg") and 7 ("debug")
        formatted as a decimal string. This field is compatible with
        syslog's priority concept.
--

[[im_systemd_field_SourceName]]
`$SourceName` (type: <<lang_type_string,string>>)::
+
--
Syslog compatibility field containing the identifier
          string (i.e. "tag").
--

[[im_systemd_field_SysInvID]]
`$SysInvID` (type: <<lang_type_string,string>>)::
+
--
Invocation ID for the runtime cycle of the
          unit the message was generated in, as available
          to processes of the unit in $INVOCATION_ID.
--

[[im_systemd_field_SystemdCGroup]]
`$SystemdCGroup` (type: <<lang_type_string,string>>)::
+
--
Control group path in the systemd hierarchy of the process the
          journal entry originates from.
--

[[im_systemd_field_SystemdOwnerUID]]
`$SystemdOwnerUID` (type: <<lang_type_string,string>>)::
+
--
Owner UID of the systemd session (if any)
          of the process the journal entry originates from.
--

[[im_systemd_field_SystemdSession]]
`$SystemdSession` (type: <<lang_type_string,string>>)::
+
--
Systemd session ID (if any) of the process the journal entry
          originates from.
--

[[im_systemd_field_SystemdSlice]]
`$SystemdSlice` (type: <<lang_type_string,string>>)::
+
--
Systemd slice unit of the process the journal entry originates from.
--

[[im_systemd_field_SystemdUnit]]
`$SystemdUnit` (type: <<lang_type_string,string>>)::
+
--
Systemd unit name (if any) of the process the journal entry
          originates from.
--

[[im_systemd_field_SystemdUserUnit]]
`$SystemdUserUnit` (type: <<lang_type_string,string>>)::
+
--
Systemd user session unit name (if any) of the process the
          journal entry originates from.
--

[[im_systemd_field_Transport]]
`$Transport` (type: <<lang_type_string,string>>)::
+
--
Transport of the entry to the journal service. Available values are:
          audit, driver, syslog, journal, stdout, kernel.
--

[[im_systemd_field_User]]
`$User` (type: <<lang_type_string,string>>)::
+
--
User ID of the process the journal entry originates from.
--

