:module: im_perl
[[im_perl]]
[desc="Provides a Perl API for generating log data"]
==== Perl (im_perl)

include::../extension/perl.adoc[tag=about]

This module makes it possible to execute Perl code in an input module
to capture and inject event data directly into {ProductName}. See also
the <<om_perl,om_perl>> and <<xm_perl,xm_perl>> modules.

The module will parse the file specified in the
<<im_perl_config_perlcode,PerlCode>> directive when {ProductName} starts the
module. The Perl code must implement the _read_data_ subroutine which will be
called by the module. To generate event data, the Log::Nxlog Perl module must
be included, which provides the following methods.

NOTE: To use the _im_perl_ module on Windows, a separate Perl
      environment must be installed, such as
      link:http://strawberryperl.com[Strawberry Perl]. Currently, the _im_perl_ module on Windows requires Strawberry Perl {windows-perl-version}.

include::../extension/perl.adoc[tag=log_methods]

add_input_data(event):: Pass the event record to the next module
  instance in the route. Failure to call this method will result in a
  memory leak.
logdata_new():: Create a new event record. The return value can be
  used with the _pass:c[set_field_*()]_ methods to insert data.
set_field_boolean(event, key, value):: Set the boolean value in the
  field named _key_.
set_field_integer(event, key, value):: Set the integer value in the
  field named _key_.
set_field_string(event, key, value):: Set the string value in the
  field named _key_.
set_read_timer(delay):: Set the timer in seconds to invoke the
  _read_data_ method again.

NOTE: The _set_read_timer()_ method should be called in order to invoke
      _read_data_ again. This is typically used for polling data. The
      _read_data_ method must not block.

include::../extension/perl.adoc[tag=pod]

include::../see_modules_by_pkg.adoc[]

[[im_perl_config]]
===== Configuration

The _im_perl_ module accepts the following directives in addition to the
<<config_module_common,common module directives>>.

[[im_perl_config_perlcode]]
PerlCode:: This mandatory directive expects a file containing valid
  Perl code that implements the _read_data_ subroutine. This file is
  read and parsed by the Perl interpreter.
+
[NOTE]
====
On Windows, the Perl script invoked by the *PerlCode* directive must define
the Perl library paths at the beginning of the script to provide access to the
Perl modules.

.nxlog-windows.pl
[source,perl]
----
include::../../../../../test/modules/extension/perl/nxlog-windows.pl[]
----
====

[[im_perl_config_config]]
Config:: This optional directive allows you to pass configuration strings
  to the script file defined by the <<im_perl_config_perlcode, PerlCode>>
  directive. This is a block directive and any text enclosed within
  `<Config></Config>` is submitted as a single string literal to the Perl code.
+
NOTE: If you pass several values using this directive (for example,
separated by the `\n` delimiter) be sure to parse the string correspondingly
inside the Perl code.

[[im_perl_config_call]]
Call:: This optional directive specifies the Perl subroutine to invoke. With
  this directive, you can call only specific subroutines from your Perl code.
  If the directive is not specified, the default subroutine `read_data` is invoked.

[[im_perl_config_examples]]
===== Examples

[[im_perl_example1]]
.Using im_perl to Generate Event Data
====
In this example, logs are generated by a Perl function that increments
a counter and inserts it into the generated line.

.nxlog.conf
[source,config]
----
include::../../../../../test/modules/input/perl/im_perl.conf[lines=7..-1]
----

.perl-input.pl
[source,perl]
----
include::../../../../../test/modules/input/perl/perl-input.pl[lines=4..-1]
----
====
